pipeline {
    agent any

    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/iwashitah/project-examples.git"
            }
        }
        
        stage ('Artifactory configuration') {
            steps {
                rtServer (
                    id: "ARTIFACTORY_SERVER",
                    url: SERVER_URL,
                    credentialsId: CREDENTIALS
                )
            }
        }

        stage ('Build docker image') {
            steps {
                script {
                    docker.build(ARTIFACTORY_DOCKER_REGISTRY + '/alpine:3.3', 'jenkins-examples/pipeline-examples/resources')
                }
            }
        }

        stage ('Push image to Artifactory') {
            steps {
                rtDockerPush(
                    serverId: "ARTIFACTORY_SERVER",
                    project: "proj1",
                    image: ARTIFACTORY_DOCKER_REGISTRY + '/alpine:3.3',
                    // Host:
                    // On OSX: "tcp://127.0.0.1:1234"
                    // On Linux can be omitted or null
                    // host: HOST_NAME,
                    targetRepo: 'proj1-docker-virtual',
                    // Attach custom properties to the published artifacts:
                    properties: 'project-name=docker1;status=stable'
                )
            }
        }

        stage ('Publish build info') {
            steps {
                rtPublishBuildInfo (
                    project: "proj1",
                    serverId: "ARTIFACTORY_SERVER"
                )
            }
        }

        stage ('Xray scan') {
            steps {
                xrayScan (
                    serverId: "ARTIFACTORY_SERVER",
                    project: "proj1",
                    failBuild: false
                )
            }
        }
    }
}
